### ISSUE TITLE
Flush details after Email is sent

### ISSUE THREAD

**Issue by Swpn0neel** [Swpn0neel/swapnoneel-portfolio#11]
Fix the Contact section such that after sending the mail successfully, the details provided by the user gets flushed.

**Comment by Bharadwajshivam28** [comment]
@Swpn0neel can i fix this issue

**Comment by Swpn0neel** [comment]
Yep, go for it

**Comment by Bharadwajshivam28** [comment]
thanks

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-25 18-13-48](https://user-images.githubusercontent.com/108119109/234280600-5aa268eb-8418-4b4a-8c6d-cb112af3af0f.png)

When one submits the detail then it takes so much time to send the details as it keep displaying sending .. It has been more then 5 mins it is not sent @Swpn0neel

**Comment by Swpn0neel** [comment]
I just checked it, the service is not working currently. If you can fix it, can you create an issue... I will assign you!!

**Comment by Bharadwajshivam28** [comment]
okay creating a issue

**Comment by Swpn0neel** [comment]
Fixed this issue too!!
