### ISSUE TITLE
Contact Section not working

### ISSUE THREAD

**Issue by Swpn0neel** [Swpn0neel/swapnoneel-portfolio#15]
Once user clicks on the "Send" button it remains on the "Sending" phase and doesn't sends the e-mail.

**Comment by Donbasilpeter** [comment]
Hello there. I think your env veriables are not properly loaded into the appication. There is a proper standard method to add handle envs in a vite application. env veriables must start by VITE_ and imported by import.meta.env.BASE_URL methods.

please refer the following doc.
https://vitejs.dev/guide/env-and-mode.html

**Comment by Swpn0neel** [comment]
Thanks for the help, I have fixed the issue.
