### ISSUE TITLE
Rework the Button Animations

### ISSUE THREAD

**Issue by Swpn0neel** [Swpn0neel/swapnoneel-portfolio#8]

**Comment by Bharadwajshivam28** [comment]
please elaborate this issue

**Comment by Swpn0neel** [comment]
The current button animations when you hover on them don't fit so well with the site, a different kind of animation will enhance it.

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
can you drop some sample which buttons are like those

**Comment by Swpn0neel** [comment]
https://codepen.io/twhite96/embed/BeemVX?height=600&default-tab=result&embed-version=2#html-box

Go for this, but keep the reddish colour intact, as on the portfolio.

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Swpn0neel** [comment]
The contact section issue has been solved completely, you can work on improving the button animation.

**Comment by Bharadwajshivam28** [comment]
not got your point

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Pjha72** [comment]
can i work on this issue

**Comment by Pjha72** [comment]
https://github.com/Swpn0neel/swapnoneel-portfolio/assets/88606641/279ffb92-d701-4116-9be4-1b8fa67d3fae

**Comment by Pjha72** [comment]
Done

**Comment by Pjha72** [comment]
@Swpn0neel pls close this issues

**Comment by Swpn0neel** [comment]
Works fine, thanks!!
